# Generated by Django 4.0.4 on 2022-05-18 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='reviewcontact',
        ),
    ]
